### ISSUE TITLE
Dictionary voor algoritmes

### ISSUE THREAD

**Issue by sjdronkers** [minprog/radio_russia_demo#2]
Quinten liet aan het einde van college 2 zien hoe je een dictionary aanmaakt voor een keuzemenu. Kunnen we hier ergens de code of een tutorial voor vinden?

**Comment by Qvdpost** [comment]
Die code komt in principe niet op de github. Dat liet ik zien als extra verdieping, maar een correcte uitwerking vergt een boel meer codeerwerk dan nu snel gedaan kan worden (alles moet dan goed werken voordat ik het op de github kan zetten). Misschien heeft iemand anders er aantekeningen van gemaakt en kun je van die student de code-snippet overnemen.
